services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: develop
    volumes:
      - frankenphp-db-data:/var/lib/mysql
volumes:
  frankenphp-db-data:
